Use the cell below for your imports.

In [1]:
import numpy as np
from scipy.sparse import coo_matrix, csr_matrix
from scipy.sparse.linalg import spsolve

implement the function mat_mul_coo that takes two sparse matrices in coo and returns their product.

In [2]:
def mat_mul_coo(a: coo_matrix, b: coo_matrix) -> coo_matrix:
    if a.shape[1] != b.shape[0]:
        raise ValueError("Matrix dimensions do not match for multiplication")

    a_csr = csr_matrix(a)
    b_csr = csr_matrix(b)

    result = a_csr.dot(b_csr).tocoo()
    result.sum_duplicates()

    return result

implement the function mat_mul_csr that takes two sparse matrices in csr format and returns their product.

In [3]:
def mat_mul_csr(a: csr_matrix, b: csr_matrix) -> csr_matrix:
    if a.shape[1] != b.shape[0]:
        raise ValueError("Matrix dimensions do not match for multiplication")

    result = a.dot(b)

    return result

implement a function solve_lin_sys that takes a matrix A in csr format and a vector b as a numpy array and solves the system Ax = b.

In [23]:
def solve_lin_sys(A: csr_matrix, b: np.ndarray) -> np.ndarray:
    x = spsolve(A, b)
    return x

In [27]:
data = np.array([1, 2, 3])
row  = np.array([0, 1, 2])
col  = np.array([0, 1, 2])

sparse_matrix = coo_matrix((data, (row, col)))

In [28]:
sparse_matrix.todense()

matrix([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [29]:
u = mat_mul_coo(sparse_matrix,sparse_matrix)

In [30]:
u.todense()

matrix([[1, 0, 0],
        [0, 4, 0],
        [0, 0, 9]], dtype=int32)

In [31]:
data = np.array([1, 5, 5, 4, 5, 5])
col_indices = np.array([0, 1, 3, 8, 2, 3])
row_pointers = np.array([0, 3, 6, 3])

sparse_matrix = csr_matrix((data, col_indices, row_pointers))

dense_matrix = sparse_matrix.toarray()

print(dense_matrix)

[[1 5 0 5 0 0 0 0 0]
 [0 0 5 5 0 0 0 0 4]
 [0 0 0 0 0 0 0 0 0]]


In [32]:
dense_matrix = np.array([[1, 6, 0], [0, 1, 0], [0, 1, 3]])

# create a CSR matrix from the dense matrix
csr_matrix = csr_matrix(dense_matrix)

# print the CSR matrix
print(csr_matrix)

  (0, 0)	1
  (0, 1)	6
  (1, 1)	1
  (2, 1)	1
  (2, 2)	3


In [33]:
v= mat_mul_csr(csr_matrix,csr_matrix)

In [34]:
v.todense()

matrix([[ 1, 12,  0],
        [ 0,  1,  0],
        [ 0,  4,  9]], dtype=int32)